{
 "title": "Celery Workers Dashboard",
 "description": "Celery Workers Monitoring",
 "tags": [
  "celery",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage % App",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(docker_container_cpu_usage_percent{job=\"telegraf-docker\", container_name=\"app\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage App",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(docker_container_mem_usage{job=\"telegraf-docker\", container_name=\"app\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage % by Worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(docker_container_cpu_usage_percent{job=\"telegraf-docker\", container_name=~\"celery.*worker.*\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(docker_container_mem_usage{job=\"telegraf-docker\", container_name=~\"celery.*worker.*\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage % Redis",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(docker_container_cpu_usage_percent{job=\"telegraf-docker\", container_name=\"redis\"}) by (container_name)",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage Redis",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(docker_container_mem_usage{job=\"telegraf-docker\", container_name=\"redis\"}) by (container_name)",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage % PostgreSQL",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(docker_container_cpu_usage_percent{job=\"telegraf-docker\", container_name=\"postgres\"}) by (container_name)",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage PostgreSQL",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(docker_container_mem_usage{job=\"telegraf-docker\", container_name=\"postgres\"}) by (container_name)",
       "legendFormat": "{{container_name}}"
      }
     ]
    }
   ]
  }
 ]
}